version: "3.9"

services:
  app:
    env_file: .env
    build:
      context: .
      args:
        - DEV=true
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"